---
- name: Deploy application
  hosts: all
  gather_facts: false
  tasks:
    - name: Wait for VMs to be contactable
      wait_for_connection:
        timeout: 300  # 5 minutes
        delay: 10     # Wait 10 seconds before first attempt
      
    - name: Gather facts now that connection is ready
      setup:
  
    - name: Test connection
      ansible.builtin.ping:

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: true

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present
      become: true

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true
      become: true

    - name: Add user to docker group
      ansible.builtin.command: usermod -aG docker {{ ansible_user }}
      become: true
      changed_when: true

    - name: Reset SSH connection to pick up new group membership
      meta: reset_connection

    - name: Ensure compose directory is setup
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/compose/{{ project_name }}"
        state: directory

    - name: Ensure compose file exists
      ansible.builtin.copy:
        dest: "/home/{{ ansible_user }}/compose/{{ project_name }}/compose.yaml"
        content: "{{ compose_content }}"

    - name: Ensure mounted files exist
      ansible.builtin.copy:
        dest: "/home/{{ ansible_user }}/compose/{{ project_name }}/files/"
        src: "/tmp/{{ item }}"
      with_items: "{{ compose_files }}"

    - name: Docker start compose file
      ansible.builtin.command: 'docker compose --project-directory "/home/{{ ansible_user }}/compose/{{ project_name }}" up --remove-orphans --wait --wait-timeout 120 --yes'
